ignoredBuiltDependencies:
  - unrs-resolver

overrides:
  '@babel/core@<=7.29.0': '>=7.29.6'
  brace-expansion@<1.1.16: '>=1.1.16'
  brace-expansion@<=5.0.7: '>=5.0.8'
  brace-expansion@>=2.0.0 <2.1.2: '>=2.1.2'
  js-yaml@<3.15.0: '>=3.15.0'
  js-yaml@>=3.0.0 <3.15.0: '>=3.15.0'
  ws@>=8.0.0 <8.21.0: '>=8.21.0'
